from picarx import Picarx
import time
import mapper 
from a_star import run_astar
def run():
	car = Picarx()
	car.set_cam_tilt_angle(30)
	path = run_astar(car,(50,50),(50,51))
	car.set_cam_pan_angle(0)
	car.forward(30)
	time.sleep(1.5)
	car.forward(0)
	time.sleep(0.2)
	
    #turn right
	car.set_dir_servo_angle(-30)
	car.backward(30)
	time.sleep(0.3)
	car.backward(0)
	car.set_dir_servo_angle(30)
	car.forward(30)
	time.sleep(0.3)
	car.backward(0)
	car.set_dir_servo_angle(-30)
	car.backward(30)
	time.sleep(0.5)
	car.backward(0)
	car.set_dir_servo_angle(30)
	car.forward(30)
	time.sleep(0.5)
	car.backward(0)
	car.set_dir_servo_angle(-30)
	car.backward(30)
	time.sleep(0.5)
	car.backward(0)
	car.set_dir_servo_angle(30)
	car.forward(30)
	time.sleep(0.2)
	car.set_dir_servo_angle(0)
	car.forward(0)
	time.sleep(0.2)
	car.backward(30)
	time.sleep(0.3)
	car.backward(0)
	#side
	car.forward(30)
	time.sleep(1.5)
	car.forward(0)
	time.sleep(0.2)
	
	#turn left
	car.set_dir_servo_angle(30)
	car.backward(30)
	time.sleep(0.5)
	car.backward(0)
	car.set_dir_servo_angle(-30)
	car.forward(30)
	time.sleep(0.6)
	car.backward(0)
	car.set_dir_servo_angle(30)
	car.backward(30)
	time.sleep(0.6)
	car.backward(0)
	car.set_dir_servo_angle(-30)
	car.forward(30)
	time.sleep(0.6)
	car.backward(0)
	car.set_dir_servo_angle(30)
	car.backward(30)
	time.sleep(0.6)
	car.backward(0)
	car.set_dir_servo_angle(-30)
	car.forward(30)
	time.sleep(0.6)
	car.set_dir_servo_angle(0)
	car.forward(0)
	time.sleep(0.2)
	car.backward(30)
	time.sleep(0.3)
	car.backward(0)
	
	#forward
	car.set_dir_servo_angle(-2)
	car.forward(30)
	time.sleep(1.5)
	car.forward(0)
	time.sleep(0.2)

	path = run_astar(car,(50,50),(50,51))
	car.set_cam_pan_angle(0)

    #forward
	car.set_dir_servo_angle(-2)
	car.forward(30)
	time.sleep(3.0)
	car.forward(0)
	time.sleep(0.2)
	
    #scan
	path = run_astar(car,(50,50),(50,75))
	car.set_cam_pan_angle(0)
	
	#forward
	car.set_dir_servo_angle(-2)
	car.forward(30)
	time.sleep(2.0)
	car.forward(0)
	time.sleep(0.2)

	
    #turn right
	car.set_dir_servo_angle(-30)
	car.backward(30)
	time.sleep(0.5)
	car.backward(0)
	car.set_dir_servo_angle(30)
	car.forward(30)
	time.sleep(0.5)
	car.backward(0)
	car.set_dir_servo_angle(-30)
	car.backward(30)
	time.sleep(0.5)
	car.backward(0)
	car.set_dir_servo_angle(30)
	car.forward(30)
	time.sleep(0.5)
	car.backward(0)
	car.set_dir_servo_angle(-30)
	car.backward(30)
	time.sleep(0.5)
	car.backward(0)
	car.set_dir_servo_angle(30)
	car.forward(30)
	time.sleep(0.5)
	car.set_dir_servo_angle(0)
	car.forward(0)
	time.sleep(0.2)
	car.backward(30)
	time.sleep(0.3)
	car.backward(0)
	#side
	car.forward(30)
	time.sleep(0.5)
	car.forward(0)
	
    #scan
	car.forward(30)
	time.sleep(1.5)
	car.forward(0)
	print("<class 'list'>")
	print("['F', 20, 'East'])")
	print("Current direction: F  number: 20")
	print("Goal location reached")
	

if __name__ == "__main__":
	run()